# this code is auto generated by the tools/codegen_symbols.py
from sympy import symbols, Function

# polars_ta.ta.momentum
ts_APO, ts_AROON_aroondown, ts_AROON_aroonup, ts_MACD_macd, ts_MACD_macdhist, ts_MACD_macdsignal, ts_MOM, ts_PPO, ts_ROC, ts_ROCP, ts_ROCR, ts_ROCR100, ts_RSI, ts_RSV, ts_STOCHF_fastd, ts_TRIX, ts_WILLR = symbols('ts_APO, ts_AROON_aroondown, ts_AROON_aroonup, ts_MACD_macd, ts_MACD_macdhist, ts_MACD_macdsignal, ts_MOM, ts_PPO, ts_ROC, ts_ROCP, ts_ROCR, ts_ROCR100, ts_RSI, ts_RSV, ts_STOCHF_fastd, ts_TRIX, ts_WILLR', cls=Function)
# polars_ta.ta.overlap
ts_BBANDS_upperband, ts_DEMA, ts_EMA, ts_KAMA, ts_MIDPOINT, ts_MIDPRICE, ts_RMA, ts_TEMA, ts_TRIMA = symbols('ts_BBANDS_upperband, ts_DEMA, ts_EMA, ts_KAMA, ts_MIDPOINT, ts_MIDPRICE, ts_RMA, ts_TEMA, ts_TRIMA', cls=Function)
# polars_ta.ta.price
AVGPRICE, MEDPRICE, TYPPRICE, WCLPRICE = symbols('AVGPRICE, MEDPRICE, TYPPRICE, WCLPRICE', cls=Function)
# polars_ta.ta.statistic
ts_BETA, ts_CORREL, ts_LINEARREG, ts_LINEARREG_ANGLE, ts_LINEARREG_INTERCEPT, ts_LINEARREG_SLOPE, ts_STDDEV, ts_TSF, ts_VAR = symbols('ts_BETA, ts_CORREL, ts_LINEARREG, ts_LINEARREG_ANGLE, ts_LINEARREG_INTERCEPT, ts_LINEARREG_SLOPE, ts_STDDEV, ts_TSF, ts_VAR', cls=Function)
# polars_ta.ta.volatility
ts_ATR, ts_NATR, ts_TRANGE = symbols('ts_ATR, ts_NATR, ts_TRANGE', cls=Function)
# polars_ta.ta.volume
ts_AD, ts_ADOSC, ts_OBV = symbols('ts_AD, ts_ADOSC, ts_OBV', cls=Function)
