# this code is auto generated by the tools/codegen_symbols.py
from sympy import symbols, Function

# polars_ta.tdx.arithmetic
BETWEEN, ROUND, ROUND2 = symbols('BETWEEN, ROUND, ROUND2', cls=Function)
# polars_ta.tdx.choice
IF, IFF, IFN, VALUEWHEN = symbols('IF, IFF, IFN, VALUEWHEN', cls=Function)
# polars_ta.tdx.energy
ts_BRAR_AR, ts_BRAR_BR, ts_CR, ts_MASS, ts_PSY = symbols('ts_BRAR_AR, ts_BRAR_BR, ts_CR, ts_MASS, ts_PSY', cls=Function)
# polars_ta.tdx.logical
NOT, ts_ALL, ts_ANY, ts_CROSS, ts_DOWNNDAY, ts_EVERY, ts_EXIST, ts_EXISTR, ts_LAST, ts_LONGCROSS, ts_NDAY, ts_UPNDAY = symbols('NOT, ts_ALL, ts_ANY, ts_CROSS, ts_DOWNNDAY, ts_EVERY, ts_EXIST, ts_EXISTR, ts_LAST, ts_LONGCROSS, ts_NDAY, ts_UPNDAY', cls=Function)
# polars_ta.tdx.moving_average
ts_BBI = symbols('ts_BBI', cls=Function)
# polars_ta.tdx.over_bought_over_sold
ts_ATR, ts_BIAS, ts_CCI, ts_KDJ, ts_MFI, ts_MTM = symbols('ts_ATR, ts_BIAS, ts_CCI, ts_KDJ, ts_MFI, ts_MTM', cls=Function)
# polars_ta.tdx.pressure_support
ts_BOLL = symbols('ts_BOLL', cls=Function)
# polars_ta.tdx.reference
RANGE, ts_BARSLAST, ts_BARSLASTCOUNT, ts_BARSSINCE, ts_BARSSINCEN, ts_CUMSUM, ts_DMA, ts_EMA, ts_EXPMA, ts_EXPMEMA, ts_FILTER, ts_HOD, ts_LOD, ts_MEMA, ts_SMA, ts_SUMIF, ts_TMA = symbols('RANGE, ts_BARSLAST, ts_BARSLASTCOUNT, ts_BARSSINCE, ts_BARSSINCEN, ts_CUMSUM, ts_DMA, ts_EMA, ts_EXPMA, ts_EXPMEMA, ts_FILTER, ts_HOD, ts_LOD, ts_MEMA, ts_SMA, ts_SUMIF, ts_TMA', cls=Function)
# polars_ta.tdx.statistic
ts_AVEDEV, ts_DEVSQ, ts_SLOPE, ts_STD, ts_STDDEV, ts_STDP, ts_VAR, ts_VARP = symbols('ts_AVEDEV, ts_DEVSQ, ts_SLOPE, ts_STD, ts_STDDEV, ts_STDP, ts_VAR, ts_VARP', cls=Function)
# polars_ta.tdx.trend
ts_ADX, ts_ADXR, ts_DPO, ts_EMV, ts_MINUS_DI, ts_MINUS_DM, ts_PLUS_DI, ts_PLUS_DM = symbols('ts_ADX, ts_ADXR, ts_DPO, ts_EMV, ts_MINUS_DI, ts_MINUS_DM, ts_PLUS_DI, ts_PLUS_DM', cls=Function)
# polars_ta.tdx.volume
ts_OBV, ts_VR = symbols('ts_OBV, ts_VR', cls=Function)
